version: 0.2
phases:
  pre_build:
    commands:
      # Firebase Test Labの認証情報とプロジェクトを設定
      - echo $FIREBASE_TEST_LAB_JSON | base64 -d > firebase-test-lab.json
      - gcloud auth activate-service-account --key-file firebase-test-lab.json
      - gcloud config set project quick-echo
      # タイムゾーンをJSTにする
      - export TZ="Asia/Tokyo"
  build:
    commands:
      - ./gradlew assembleDebug
      - ./gradlew localDataStore:assembleDebugAndroidTest
      - gcloud firebase test android run --type instrumentation --app app/build/outputs/apk/debug/app-debug.apk --test localDataStore/build/outputs/apk/androidTest/debug/localDataStore-debug-androidTest.apk --device model=NexusLowRes,version=29,locale=ja_JP,orientation=portrait
      - ./gradlew testDebug
      - ./gradlew lintDebug
      - danger
