version: 0.2
env:
  variables:
    GIT_REPOSITORY_URL: git@github.com/tfandkusu/quickecho.git
phases:
  install:
    runtime-versions:
      android: latest
  build:
    commands:
      - ./gradlew testDebug
      - gem install bundler --force --no-document --version 2.1.4
      - bundle install --path vendor/bundle
      - bundle exec danger

# 環境変数を更新
