version: 0.2
phases:
  install:
    runtime-versions:
      android: latest
  build:
    commands:
      - ./gradlew testDebug
      - gem install bundler
      - bundle install --path vendor/bundle
      - bundle exec danger

# 15 GB メモリ、8 vCPUにする
