name: deploygate
# ワークフロー実行タイミングは
on:
  # stagingブランチへのPUSH
  push:
    branches:
      - staging
  # プルリクの作成と更新(テスト用)
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  check: # job名
    # ubuntuで動かす
    runs-on: ubuntu-latest
    steps:
      # 該当ブランチをチェックアウトする
      - uses: actions/checkout@v2
      # java11をセットアップする
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      # google-services.jsonを復元する
      - run: echo $GOOGLE_SERVICES_JSON | base64 -d > app/src/release/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      # KeyStoreを復元する
      - run: mkdir ~/keystores
      - run: echo $KEYSTORE | base64 -d > ~/keystores/echo.jks
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
      # Deploygateのタスクを実行する
      - run: ./gradlew uploadDeployGateRelease
        env:
          DEPLOYGATE_APP_OWNER_NAME: ${{ secrets.DEPLOYGATE_APP_OWNER_NAME }}
          DEPLOYGATE_API_TOKEN: ${{ secrets.DEPLOYGATE_API_TOKEN }}
          DEPLOYGATE_DISTRIBUTION_KEY: ${{ secrets.DEPLOYGATE_DISTRIBUTION_KEY }}
          BITRISEIO_ANDROID_KEYSTORE_ALIAS: ${{ secrets.DEPLOYGATE_API_TOKEN }}
          BITRISEIO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.BITRISEIO_ANDROID_KEYSTORE_PASSWORD }}
          BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.BITRISEIO_ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
